-- Klingenberg Food — pgTAP: generated-announcement ownership and the coordinated
-- operation (§4, §5, §6, §7e items 6 and 8, §8, §9). **Phase 8C-3A.**
--
-- 8C-1 built the replacement transaction and 8C-2 the pure generator. Neither could
-- answer the question this phase exists for:
--
--     announcement A was generated by override A and is live.
--     announcement B, generated by override B, replaces it.
--     Fortryd puts A back.
--     **Which override owns the announcement now?**
--
-- The answer is one pointer, `announcement.source_override_id`, paired with `source` in
-- both directions. `opening_hours_overrides.announcement_created` — §4's original column
-- for the job — is dropped, so there is no second store of the fact and nothing that can
-- be left stale by a statement that failed halfway.
--
-- This suite asserts, in order:
--
--    1. **the model** — the column, its foreign key, the pairing CHECK, the twelfth
--       grant, and that `announcement_created` is gone;
--    2. **the boundary** — every function invoker-rights with a pinned `search_path`,
--       nothing new that is SECURITY DEFINER, and `anon` refused at both new functions
--       and at the column itself;
--    3. **the coordinator** — from real Staff and Owner JWTs: an empty announcement
--       applies, an **active** one returns `conflict` with **zero writes and no audit
--       row**, and only an explicit confirmation replaces it;
--    4. **hidden, expired and empty** proceed without a false conflict;
--    5. **the sequential case the brief names** — A, then B replacing A, then Fortryd:
--       ownership moves with the message, one override owns it at a time, the snapshot
--       knows the previous owner, and the undo is one level with no stack;
--    6. **manual → generated → restore**, with a pending draft byte-identical
--       throughout and no override owning the restored manual message;
--    7. **hidden and expired previous states**, restored exactly, ownership included;
--    8. **the refusals** — a stale announcement token, a stale override token, an
--       override that is not published, and both halves of the pairing rule; none of
--       them writes, and none of them logs;
--    9. **§7e item 6's model** — the removal refuses while the override owns the
--       announcement, or the one still stashed for Fortryd.
--
-- **Forging the ownership pointer is asserted in `016`, not here**, and deliberately:
-- `source_override_id` is a trusted lifecycle column in §0l's sense, so it belongs in
-- the suite that owns that model, beside `previous`, `replaced_at` and `source`. `016`
-- refuses it directly and paired with `source`, from real Staff and Owner JWTs. What
-- this suite asserts about it is the layer underneath — that the *pair* is not storable
-- in a broken state even by the role the write guard steps aside for.
--
-- Prerequisite: `npm run db:users` has created owner@example.test and
-- staff@example.test, as for 005–016.

begin;
create extension if not exists pgtap with schema extensions;

select plan(111);

-- ---------------------------------------------------------------------------
-- Fixtures
-- ---------------------------------------------------------------------------

select is(
  (select count(*) from auth.users where email in ('owner@example.test', 'staff@example.test')),
  2::bigint,
  'both local development identities exist (run `npm run db:users` if this fails)');

delete from public.audit_log;

select set_config('test.staff_uid',
  (select id from auth.users where email = 'staff@example.test')::text, true);
select set_config('test.owner_uid',
  (select id from auth.users where email = 'owner@example.test')::text, true);

create function pg_temp.become(uid text, email text)
returns void
language plpgsql
as $fn$
begin
  perform set_config('request.jwt.claims',
    json_build_object('sub', uid, 'role', 'authenticated', 'email', email)::text, true);
  execute 'set local role authenticated';
end;
$fn$;

create function pg_temp.become_staff() returns void language sql as $fn$
  select pg_temp.become(current_setting('test.staff_uid'), 'staff@example.test');
$fn$;

create function pg_temp.become_owner() returns void language sql as $fn$
  select pg_temp.become(current_setting('test.owner_uid'), 'owner@example.test');
$fn$;

create function pg_temp.become_anon()
returns void
language plpgsql
as $fn$
begin
  perform set_config('request.jwt.claims', '{"role":"anon"}', true);
  execute 'set local role anon';
end;
$fn$;

create function pg_temp.version() returns timestamptz language sql as $fn$
  select updated_at from public.announcement limit 1
$fn$;

create function pg_temp.owner_of() returns uuid language sql as $fn$
  select source_override_id from public.announcement limit 1
$fn$;

create function pg_temp.previous_owner() returns uuid language sql as $fn$
  select (previous ->> 'source_override_id')::uuid from public.announcement limit 1
$fn$;

create function pg_temp.audit_total() returns bigint language sql security definer set search_path = '' as $fn$
  select count(*) from public.audit_log
$fn$;

/*
 * The whole row, minus the two columns a legitimate write is *expected* to move, as one
 * jsonb value — 016's own probe, for the same reason: an assertion that only checks "it
 * refused" would pass against a table that had already been written to.
 */
create function pg_temp.row_state() returns jsonb language sql security definer set search_path = ''
as $fn$
  select to_jsonb(a) - 'updated_at' - 'updated_by' from public.announcement a limit 1
$fn$;

/*
 * Two published one-off changes, A and B, and their version tokens.
 *
 * Both are dated ahead, so `overrides_select_public` and the administration's own
 * "today onwards" list would each accept them. They carry *different* content because
 * the sequential case below is about two different overrides owning two different
 * messages — but nothing in this suite reads their content: the message is composed
 * above the database, by the 8C-2 generator, and reaches the coordinator as a string.
 */
insert into public.opening_hours_overrides (date, kind, opens_at, closes_at, status)
values (((now() at time zone 'Europe/Copenhagen')::date + 3), 'custom', '17:00', '19:00', 'published'),
       (((now() at time zone 'Europe/Copenhagen')::date + 4), 'closed', null, null, 'published'),
       (((now() at time zone 'Europe/Copenhagen')::date + 5), 'custom', '13:00', '18:00', 'draft');

select set_config('test.override_a',
  (select id from public.opening_hours_overrides
    where date = ((now() at time zone 'Europe/Copenhagen')::date + 3))::text, true);
select set_config('test.override_b',
  (select id from public.opening_hours_overrides
    where date = ((now() at time zone 'Europe/Copenhagen')::date + 4))::text, true);
select set_config('test.override_pending',
  (select id from public.opening_hours_overrides
    where date = ((now() at time zone 'Europe/Copenhagen')::date + 5))::text, true);

create function pg_temp.a() returns uuid language sql as $fn$
  select current_setting('test.override_a')::uuid
$fn$;
create function pg_temp.b() returns uuid language sql as $fn$
  select current_setting('test.override_b')::uuid
$fn$;
create function pg_temp.pending() returns uuid language sql as $fn$
  select current_setting('test.override_pending')::uuid
$fn$;

create function pg_temp.ov(p_id uuid) returns timestamptz language sql as $fn$
  select updated_at from public.opening_hours_overrides where id = p_id
$fn$;

/*
 * The starting state: **no announcement at all**, with a pending manual draft behind it.
 *
 * The draft is part of the fixture rather than an afterthought, for the reason 015
 * records: a generated announcement is not a publish, so a draft somebody was in the
 * middle of writing must be byte-identical before the operation, after it, and after
 * the Fortryd that follows.
 *
 * SECURITY DEFINER, so it runs as the table owner. That is not an exemption a session
 * can put on: `tg_guard_announcement_write()` steps aside for `postgres` and
 * `service_role` because a migration, the seed and a fixture are not browser sessions,
 * and `authenticated` is a member of neither role.
 */
create function pg_temp.reset_empty() returns void language sql security definer set search_path = '' as $fn$
  update public.announcement
     set message            = null,
         link_type          = 'none',
         link_page          = null,
         link_url           = null,
         link_label         = null,
         expires_at         = null,
         is_visible         = false,
         source             = 'manual',
         source_override_id = null,
         previous           = null,
         replaced_at        = null,
         draft              = jsonb_build_object('message', 'Kladde C — endnu ikke offentliggjort');
$fn$;

/* The same, with a published, visible, **manual** message A standing on the site. */
create function pg_temp.reset_manual(p_visible boolean, p_expires interval)
returns void language plpgsql security definer set search_path = '' as $fn$
begin
  update public.announcement
     set message            = 'Besked A — den der stod der',
         link_type          = 'page',
         link_page          = '/menu',
         link_url           = null,
         link_label         = 'Se menuen',
         expires_at         = pg_catalog.now() + p_expires,
         is_visible         = p_visible,
         source             = 'manual',
         source_override_id = null,
         previous           = null,
         replaced_at        = null,
         draft              = jsonb_build_object('message', 'Kladde C — endnu ikke offentliggjort');
end;
$fn$;

/* One call to the coordinator, with the two tokens read from the rows themselves. */
create function pg_temp.apply(p_override uuid, p_message text, p_confirm boolean default false)
returns jsonb language sql as $fn$
  select public.apply_generated_announcement(
    p_override, pg_temp.ov(p_override), p_message,
    'page', '/find-os', null, 'Se tider',
    pg_catalog.now() + interval '2 days', pg_temp.version(), p_confirm)
$fn$;


-- ===========================================================================
-- 1. The model
-- ===========================================================================

select has_column('public', 'announcement', 'source_override_id',
  'the announcement carries the override that owns it');

select col_type_is('public', 'announcement', 'source_override_id', 'uuid',
  'and it is a row id, never a date, a weekday or a message');

select is(
  (select count(*) from information_schema.columns
    where table_schema = 'public' and table_name = 'opening_hours_overrides'
      and column_name = 'announcement_created'),
  0::bigint,
  'announcement_created is gone — one pointer, and no second store of the same fact');

/*
 * "At most one override owns the current announcement" is **structural** rather than
 * constrained: there is one announcement row, it holds one `source_override_id`, and one
 * column cannot hold two values. No partial unique index is needed and none exists — an
 * index could only make a duplicate unlikely to be written, and there is nowhere here
 * for a duplicate to live.
 */
select is(
  (select count(*) from pg_constraint
    where conrelid = 'public.announcement'::regclass and conname = 'announcement_singleton_unique'),
  1::bigint,
  'the announcement is a singleton, which is what makes "one owner at a time" structural');

select is(
  (select count(*) from pg_constraint
    where conrelid = 'public.announcement'::regclass
      and conname = 'announcement_source_owner_check' and contype = 'c'),
  1::bigint,
  'the source/owner pairing is a CHECK constraint, in both directions');

select is(
  (select confdeltype from pg_constraint
    where conrelid = 'public.announcement'::regclass and contype = 'f'
      and confrelid = 'public.opening_hours_overrides'::regclass),
  'r'::"char",
  'and the foreign key restricts deletion — an owning override cannot be removed under it');

-- Both halves of the pairing, refused as data rather than as policy: this runs as the
-- table owner, for whom the write guard steps aside, so the CHECK is the only thing
-- standing there.
select throws_ok(
  $$ update public.announcement set source = 'opening_hours' $$,
  '23514', null, 'a generated announcement with no owner is not storable, even by the owner role');

select throws_ok(
  $$ update public.announcement set source_override_id = (select id from public.opening_hours_overrides limit 1) $$,
  '23514', null, 'and neither is a manual one that names an override');

select set_eq(
  $$ select column_name::text
       from information_schema.column_privileges
      where table_schema = 'public' and table_name = 'announcement'
        and grantee = 'authenticated' and privilege_type = 'UPDATE' $$,
  array['draft', 'message', 'link_type', 'link_page', 'link_url', 'link_label',
        'expires_at', 'is_visible', 'source', 'source_override_id', 'previous', 'replaced_at'],
  'authenticated holds UPDATE on twelve named columns — the ownership pointer is the twelfth');


-- ===========================================================================
-- 2. The boundary: invoker rights, pinned paths, and anon
-- ===========================================================================

select is(
  (select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname in ('apply_generated_announcement', 'announcement_replacement_kind',
                        'replace_announcement', 'restore_announcement')
      and p.prosecdef),
  0::bigint,
  'the coordinator and everything it composes are SECURITY INVOKER — RLS still decides');

select is(
  (select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname in ('apply_generated_announcement', 'announcement_replacement_kind',
                        'replace_announcement', 'restore_announcement')
      and p.proconfig @> array['search_path=""']),
  4::bigint,
  'and all four pin an empty search_path');

select is(
  (select count(*) from information_schema.column_privileges
    where table_schema = 'public' and table_name = 'announcement'
      and grantee = 'anon' and column_name = 'source_override_id'),
  0::bigint,
  'a guest may neither read nor write the ownership pointer — it is administration state');

select pg_temp.become_anon();

select throws_ok(
  $$ select public.apply_generated_announcement(
       null::uuid, null::timestamptz, 'Besked', 'none', null, null, null,
       now() + interval '1 day', now(), false) $$,
  '42501', null, 'anon meets the coordinator''s grant before RLS is ever consulted');

select throws_ok(
  $$ select source_override_id from public.announcement $$,
  '42501', null, 'and cannot read the pointer from a real anonymous JWT');

reset role;


-- ===========================================================================
-- 3. The coordinator, from a real Staff JWT
-- ===========================================================================

select pg_temp.reset_empty();
delete from public.audit_log;
select set_config('test.draft', (select draft::text from public.announcement), true);
select pg_temp.become_staff();

select is(
  (select pg_temp.apply(pg_temp.a(), 'Ændrede åbningstider fredag · 17:00–19:00') ->> 'status'),
  'applied',
  'staff may publish the generated announcement when nothing stands in its way');

select is((select message from public.announcement), 'Ændrede åbningstider fredag · 17:00–19:00',
  'the message is live');
select is((select source from public.announcement), 'opening_hours',
  'the source is generated — and the browser never sent it: the coordinator has no such parameter');
select is(pg_temp.owner_of(), pg_temp.a(),
  'override A owns it');
select ok((select is_visible from public.announcement),
  'and it went live — 1ae: "Den nye besked går live"');
select isnt((select replaced_at from public.announcement), null,
  'replaced_at is stamped, in the same statement');

select is((select draft::text from public.announcement), current_setting('test.draft'),
  'the pending manual draft is byte-identical — a generated announcement is not a publish');

reset role;
select is(pg_temp.audit_total(), 1::bigint,
  'one real write, one audit row');
select is(
  (select after ->> 'source_override_id' from public.audit_log
    where entity = 'announcement' order by created_at desc limit 1),
  pg_temp.a()::text,
  'and the audit row carries the ownership, so the move is legible afterwards');


-- ===========================================================================
-- 4. §7e item 8 — an active announcement is a conflict, and writes nothing
-- ===========================================================================

select pg_temp.reset_manual(true, interval '3 days');
delete from public.audit_log;
select set_config('test.before', pg_temp.row_state()::text, true);
select pg_temp.become_staff();

select is(
  (select pg_temp.apply(pg_temp.a(), 'Ændrede åbningstider fredag · 17:00–19:00') ->> 'status'),
  'conflict',
  'the first attempt against an active announcement is a conflict, not a replacement');

select is(
  (select pg_temp.apply(pg_temp.a(), 'Ændrede åbningstider fredag · 17:00–19:00') ->> 'conflict'),
  'active',
  'and it says which of the four states it found — the only one a guest can read');

select is(
  (select pg_temp.apply(pg_temp.a(), 'Ændrede åbningstider fredag · 17:00–19:00')
     -> 'current' ->> 'message'),
  'Besked A — den der stod der',
  'it names the message standing in the way, read from the row rather than from the caller');

reset role;
select is(pg_temp.row_state(), current_setting('test.before')::jsonb,
  'three refused attempts and the announcement is byte-identical — zero writes');
select is(pg_temp.audit_total(), 0::bigint,
  'and nothing was logged: a conflict is a question, not an event');

-- The half §7e item 8 exists for: the hours the caller published a moment ago are
-- untouched, because there is no statement in the refusing branch at all.
select is(
  (select count(*) from public.opening_hours_overrides where status = 'published'),
  2::bigint,
  'and both published overrides are still published — a conflict cannot roll the hours back');


-- ===========================================================================
-- 5. The confirmation, and only the confirmation, replaces
-- ===========================================================================

select pg_temp.become_staff();

select is(
  (select pg_temp.apply(pg_temp.a(), 'Ændrede åbningstider fredag · 17:00–19:00', true) ->> 'status'),
  'applied',
  'an explicit confirmation replaces the active announcement');

select is((select message from public.announcement), 'Ændrede åbningstider fredag · 17:00–19:00',
  'the generated message is live');
select is(pg_temp.owner_of(), pg_temp.a(),
  'override A owns it');
select is((select previous ->> 'message' from public.announcement), 'Besked A — den der stod der',
  'and the manual message it displaced is stashed for Fortryd');
select is(pg_temp.previous_owner(), null,
  'stashed with no owner, because the message it displaced was manual');

reset role;
select is(pg_temp.audit_total(), 1::bigint,
  'one confirmation, one audit row — the three refusals before it logged nothing');


-- ===========================================================================
-- 6. Hidden, expired and empty are not public conflicts
-- ===========================================================================

select pg_temp.reset_manual(false, interval '3 days');
select pg_temp.become_staff();
select is(
  (select pg_temp.apply(pg_temp.a(), 'Besked fra en skjult tilstand') ->> 'status'),
  'applied',
  'a switched-off message is replaced without a sheet — no guest could read it');
select is(
  (select previous ->> 'is_visible' from public.announcement),
  'false',
  'and it is stashed switched off, so Fortryd puts it back the way it stood');
reset role;

select pg_temp.reset_manual(true, interval '-1 hour');
select pg_temp.become_staff();
select is(
  (select pg_temp.apply(pg_temp.a(), 'Besked fra en udløbet tilstand') ->> 'status'),
  'applied',
  'an expired message is replaced without a sheet either');
reset role;

select pg_temp.reset_empty();
select pg_temp.become_staff();
select is(
  (select pg_temp.apply(pg_temp.a(), 'Besked fra ingenting') ->> 'status'),
  'applied',
  'and replacing nothing is allowed, and is not dressed up as a conflict');
select is(
  (select pg_temp.apply(pg_temp.a(), 'Irrelevant') ->> 'status'),
  'conflict',
  'the message it just published is now active, so the next attempt asks — the state is re-read every time');
reset role;


-- ===========================================================================
-- 7. The sequential case: A, then B, then Fortryd
-- ===========================================================================
--
-- The brief's own scenario, and the one nothing in the schema could answer before this
-- phase.

select pg_temp.reset_empty();
delete from public.audit_log;
select set_config('test.draft', (select draft::text from public.announcement), true);
select pg_temp.become_staff();

select is(
  (select pg_temp.apply(pg_temp.a(), 'Besked A — genereret af A') ->> 'status'),
  'applied', 'A generates announcement A');
select is(pg_temp.owner_of(), pg_temp.a(), 'and A owns it');

select is(
  (select pg_temp.apply(pg_temp.b(), 'Besked B — genereret af B', true) ->> 'status'),
  'applied', 'B generates announcement B, which replaces A');

select is((select message from public.announcement), 'Besked B — genereret af B',
  'B is current');
select is(pg_temp.owner_of(), pg_temp.b(),
  'B owns the announcement');
select isnt(pg_temp.owner_of(), pg_temp.a(),
  'A does not currently own it');
select is(pg_temp.previous_owner(), pg_temp.a(),
  'and the snapshot knows that what it displaced belonged to A');
select is((select previous ->> 'source' from public.announcement), 'opening_hours',
  'stashed as the generated message it was, not as a manual one');

-- The invariant, asked of the whole table rather than of one row.
select is(
  (select count(*) from public.opening_hours_overrides o
     join public.announcement a on a.source_override_id = o.id),
  1::bigint,
  'exactly one override owns the current announcement — never two');

select is(
  (select public.restore_announcement(pg_temp.version()) ->> 'status'),
  'restored',
  'Fortryd puts A back');

select is((select message from public.announcement), 'Besked A — genereret af A',
  'A has returned');
select is(pg_temp.owner_of(), pg_temp.a(),
  'and A owns it again — ownership came back with the message, in one statement');
select isnt(pg_temp.owner_of(), pg_temp.b(),
  'B no longer owns it');
select is(
  (select count(*) from public.opening_hours_overrides o
     join public.announcement a on a.source_override_id = o.id),
  1::bigint,
  'still exactly one owner — no duplicate current-owner flag, because there is no flag');
select is((select previous from public.announcement), null,
  'the snapshot is cleared — one level, no stack');
select is(
  (select public.restore_announcement(pg_temp.version()) ->> 'status'),
  'nothing_to_restore',
  'and a second Fortryd is a refusal rather than a second undo');

-- Replacing again after the restore: the one-level undo is intact, not exhausted.
select is(
  (select pg_temp.apply(pg_temp.b(), 'Besked B — igen', true) ->> 'status'),
  'applied', 'B may replace A again after the restore');
select is(pg_temp.owner_of(), pg_temp.b(), 'B owns it again');
select is(pg_temp.previous_owner(), pg_temp.a(), 'and A is the stashed owner again');

select is((select draft::text from public.announcement), current_setting('test.draft'),
  'the pending manual draft is byte-identical through all five writes');

reset role;
select is(pg_temp.audit_total(), 4::bigint,
  'four real writes, four audit rows: apply, apply, restore, apply');


-- ===========================================================================
-- 8. Manual → generated → restore
-- ===========================================================================

select pg_temp.reset_manual(true, interval '3 days');
delete from public.audit_log;
select set_config('test.draft', (select draft::text from public.announcement), true);
select pg_temp.become_staff();

select is(
  (select pg_temp.apply(pg_temp.b(), 'Besked B — genereret af B', true) ->> 'status'),
  'applied', 'a generated message replaces the manual one');
select is(pg_temp.owner_of(), pg_temp.b(), 'B owns it');

select is(
  (select public.restore_announcement(pg_temp.version()) ->> 'status'),
  'restored', 'Fortryd restores the manual message');

select is((select message from public.announcement), 'Besked A — den der stod der',
  'the manual message is back');
select is((select source from public.announcement), 'manual',
  'and it calls itself manual again');
select is(pg_temp.owner_of(), null,
  'no override owns the current announcement — B''s ownership was cleared by the same statement');
select is(
  (select count(*) from public.opening_hours_overrides o
     join public.announcement a on a.source_override_id = o.id),
  0::bigint,
  'and no override anywhere claims it');

select is((select draft::text from public.announcement), current_setting('test.draft'),
  'the draft is byte-identical through the whole operation');

reset role;


-- ===========================================================================
-- 9. A hidden and an expired previous, restored exactly
-- ===========================================================================
--
-- 8C-1's semantics, unchanged, with ownership added: ownership describes what the
-- singleton represents, not whether RLS currently renders it.

select pg_temp.reset_manual(false, interval '3 days');
select pg_temp.become_staff();
select is((select pg_temp.apply(pg_temp.a(), 'Genereret over en skjult besked') ->> 'status'),
  'applied', 'a hidden manual message is displaced');
select is((select public.restore_announcement(pg_temp.version()) ->> 'status'),
  'restored', 'and restored');
select ok(not (select is_visible from public.announcement),
  'it comes back switched off — exactly as it stood');
reset role;

select pg_temp.reset_manual(true, interval '-1 hour');
select set_config('test.expiry', (select expires_at::text from public.announcement), true);
select pg_temp.become_staff();
select is((select pg_temp.apply(pg_temp.a(), 'Genereret over en udløbet besked') ->> 'status'),
  'applied', 'an expired manual message is displaced');
select is((select public.restore_announcement(pg_temp.version()) ->> 'showable'),
  'false', 'the restore reports that a guest cannot read what came back');
select is((select expires_at::text from public.announcement), current_setting('test.expiry'),
  'and the expiry is exactly what it was — nothing was extended to make the undo look successful');
reset role;

-- A generated previous that is not currently guest-visible still restores its owner.
select pg_temp.reset_empty();
select pg_temp.become_staff();
select is((select pg_temp.apply(pg_temp.a(), 'Genereret af A') ->> 'status'), 'applied',
  'A generates a message');
reset role;
-- Switched off through the immediate path, so the thing B displaces is a *hidden
-- generated* announcement.
select pg_temp.become_staff();
select is((select public.set_announcement_visible(false, pg_temp.version()) ->> 'status'),
  'updated', 'somebody switches it off');
select is((select pg_temp.apply(pg_temp.b(), 'Genereret af B') ->> 'status'), 'applied',
  'B replaces it without a conflict — a hidden message is not a public one');
select is(pg_temp.previous_owner(), pg_temp.a(),
  'and the hidden generated message is stashed with A''s ownership intact');
select is((select public.restore_announcement(pg_temp.version()) ->> 'status'), 'restored',
  'the restore puts it back');
select is(pg_temp.owner_of(), pg_temp.a(),
  'A owns it again, even though no guest can see it — ownership is what the row represents');
select ok(not (select is_visible from public.announcement),
  'and it is still switched off');
reset role;


-- ===========================================================================
-- 10. The refusals, and that none of them writes or logs
-- ===========================================================================

select pg_temp.reset_empty();
delete from public.audit_log;
select set_config('test.before', pg_temp.row_state()::text, true);
select pg_temp.become_staff();

select is(
  (select public.apply_generated_announcement(
     pg_temp.a(), pg_temp.ov(pg_temp.a()), 'Besked', 'none', null, null, null,
     now() + interval '1 day', now() - interval '1 day', false) ->> 'status'),
  'stale_announcement',
  'a stale announcement token refuses — and is not the same word as 1ae''s conflict');

select is(
  (select public.apply_generated_announcement(
     pg_temp.a(), now() - interval '1 day', 'Besked', 'none', null, null, null,
     now() + interval '1 day', pg_temp.version(), false) ->> 'status'),
  'stale_override',
  'a stale override token refuses too — the message may no longer describe those hours');

select is(
  (select pg_temp.apply(pg_temp.pending(), 'Besked om noget der ikke er offentliggjort')
     ->> 'reason'),
  'source_override',
  'an override that is not on the hjemmeside yet is refused — §7e item 8''s ordering');

select is(
  (select public.apply_generated_announcement(
     null::uuid, now(), 'Besked', 'none', null, null, null,
     now() + interval '1 day', pg_temp.version(), false) ->> 'status'),
  'invalid_payload',
  'and an operation naming no override at all is refused before anything is read');

-- The pairing rule, through the mechanism the coordinator composes.
select is(
  (select public.replace_announcement('Besked', 'none', null, null, null,
     now() + interval '1 day', 'opening_hours', pg_temp.version(), null) ->> 'reason'),
  'source_override',
  'replace_announcement refuses a generated announcement with no owner');

select is(
  (select public.replace_announcement('Besked', 'none', null, null, null,
     now() + interval '1 day', 'manual', pg_temp.version(), pg_temp.a()) ->> 'reason'),
  'source_override',
  'and refuses a manual one that names an override');

select is(
  (select public.replace_announcement('Besked', 'none', null, null, null,
     now() + interval '1 day', 'opening_hours', pg_temp.version(),
     '00000000-0000-4000-8000-000000000000'::uuid) ->> 'reason'),
  'source_override',
  'and one that names an override this system does not have');

reset role;
select is(pg_temp.row_state(), current_setting('test.before')::jsonb,
  'seven refusals and the announcement is byte-identical');
select is(pg_temp.audit_total(), 0::bigint,
  'and none of them wrote an audit row');

-- A manual replacement that says nothing about ownership is still accepted: the
-- parameter's default is the safe half of the pair, and this is what says so.
select pg_temp.become_staff();
select is(
  (select public.replace_announcement('En manuel erstatning', 'none', null, null, null,
     now() + interval '1 day', 'manual', pg_temp.version()) ->> 'status'),
  'replaced',
  'a manual replacement may omit the ownership parameter entirely');
select is(pg_temp.owner_of(), null,
  'and the omission means "no override", which is the only thing it can mean');
reset role;


-- ===========================================================================
-- 11. The Owner reaches all of it too (§5: both rows of the matrix)
-- ===========================================================================

select pg_temp.reset_empty();
select pg_temp.become_owner();

select is(
  (select pg_temp.apply(pg_temp.a(), 'Ejerens genererede besked') ->> 'status'),
  'applied',
  'an owner may coordinate a generated announcement');
select is(pg_temp.owner_of(), pg_temp.a(),
  'with the same ownership move');
select is(
  (select public.restore_announcement(pg_temp.version()) ->> 'status'),
  'restored',
  'and may undo it');

reset role;


-- ===========================================================================
-- 12. §7e item 6's model — the removal refuses while the override owns
-- ===========================================================================
--
-- **The model, not the consequence.** *"Ask, and default to removing the announcement
-- too"* is 8C-3B's. What this phase owes it is a database that can answer "does this
-- override own the message on the hjemmeside?" without reading a word of that message —
-- and a removal that cannot silently orphan one in the meantime.

select pg_temp.reset_empty();
select pg_temp.become_staff();
select is((select pg_temp.apply(pg_temp.a(), 'Genereret af A') ->> 'status'), 'applied',
  'A owns the announcement');

select is(
  (select public.remove_opening_hours_override(pg_temp.a(), pg_temp.ov(pg_temp.a())) ->> 'status'),
  'owns_announcement',
  'so removing A is refused, with a status a screen can word');

select is(
  (select public.remove_opening_hours_override(pg_temp.b(), pg_temp.ov(pg_temp.b())) ->> 'status'),
  'removed',
  'while B, which owns nothing, is removed as it always was');

-- The other half: an override that owns only the *stashed* announcement is holding a
-- Fortryd, and deleting it would turn that Fortryd into `owner_missing`.
reset role;
select pg_temp.reset_empty();
select pg_temp.become_staff();
select is((select pg_temp.apply(pg_temp.a(), 'Genereret af A') ->> 'status'), 'applied',
  'A owns the announcement again');
reset role;

-- A second override to displace it with, since B was removed above.
insert into public.opening_hours_overrides (date, kind, opens_at, closes_at, status)
values (((now() at time zone 'Europe/Copenhagen')::date + 6), 'closed', null, null, 'published');
select set_config('test.override_c',
  (select id from public.opening_hours_overrides
    where date = ((now() at time zone 'Europe/Copenhagen')::date + 6))::text, true);

select pg_temp.become_staff();
select is(
  (select public.apply_generated_announcement(
     current_setting('test.override_c')::uuid,
     pg_temp.ov(current_setting('test.override_c')::uuid),
     'Genereret af C', 'none', null, null, null,
     now() + interval '2 days', pg_temp.version(), true) ->> 'status'),
  'applied',
  'C displaces it');

select is(pg_temp.previous_owner(), pg_temp.a(),
  'so A owns only the stashed announcement now');

/*
 * Phase 8C-3B changed this half, and §18 of the brief is why.
 *
 * 8C-3A refused the deletion, because a snapshot naming a deleted row would turn the next
 * Fortryd into `owner_missing`. But refusing forever is not an answer either: the person is
 * deleting the very hours that snapshot describes, and there is no second outcome in which
 * putting it back would mean anything. So the trusted removal now **resolves** it — the
 * obsolete stash is discarded inside the same transaction, the current announcement is left
 * alone, and the override goes.
 */
-- One call, two assertions: the removal is not idempotent and must not be issued twice
-- just to look at its reply from two angles.
create temp table removal_of_a as
  select public.remove_opening_hours_override(pg_temp.a(), pg_temp.ov(pg_temp.a())) as reply;

select is(
  (select reply ->> 'status' from removal_of_a),
  'removed',
  'removing A now succeeds: the stash it held is resolved rather than refused forever');

select is(
  (select reply ->> 'discarded_previous' from removal_of_a),
  'true',
  'and the reply says which cleanup it had to do');

reset role;
select is(
  (select count(*) from public.opening_hours_overrides where id = pg_temp.a()),
  0::bigint,
  'A is gone');

select is(
  (select previous from public.announcement),
  null,
  'the obsolete stash is gone with it — no Fortryd can now point at a row that is not there');

select is(
  (select replaced_at from public.announcement),
  null,
  'and replaced_at goes with the snapshot it timed');

-- The half that must NOT move: C still owns the message a guest is reading.
select is(
  (select message from public.announcement),
  'Genereret af C',
  'the current announcement is untouched — only the stash was obsolete');

select is(
  (select source_override_id from public.announcement),
  current_setting('test.override_c')::uuid,
  'and C still owns it');

select is(
  (select count(*)::int from public.audit_log
    where entity = 'announcement' and action = 'discard_previous'),
  1,
  'the discard is audited, so a Fortryd that later fails has something to explain it');


select * from finish();
rollback;
