/**
 * Who owns the announcement — design 1t, 1ae; technical plan §4, §7e items 6 and 8.
 *
 * The announcement is a singleton, and it came from exactly one of two places: a
 * person wrote it at `/admin/besked` (1ad), or a one-off opening-hours change
 * generated it (1t). This module is that sentence as a type, and it exists because
 * phase 8C-3 has to answer a question the earlier phases never had to:
 *
 *     announcement A was generated by override A and is live.
 *     announcement B, generated by override B, replaces it.
 *     Fortryd puts A back.
 *     **Which override owns the announcement now?**
 *
 * ONE POINTER, NOT A FLAG PER OVERRIDE
 *
 * The answer is `announcement.source_override_id`, and it is the *only* representation
 * of this fact in the system. `opening_hours_overrides.announcement_created` — §4's
 * original column for the job — was dropped in
 * `supabase/migrations/20260831180000_generated_announcement_ownership.sql`, for two
 * reasons recorded there in full and worth one line here: a boolean per override is a
 * cache of a join that a half-finished write can leave stale, and it would have needed
 * a second column-privilege guard on a second table to be trustworthy.
 *
 * So "does this override own the current announcement?" is
 * {@link isOwnedByOverride} — derived from the singleton, never stored twice, and
 * therefore never able to disagree with itself. And "at most one override owns it" is
 * structural: one row, one column, one value.
 *
 * NOTHING HERE READS A MESSAGE
 *
 * §7e item 6 asks whether a generated announcement *"points at that date"*. It is
 * answered by comparing ids, never by parsing the message, the weekday, the formatted
 * date, the expiry or the link label. The suggested wording is editable by design
 * (§0m), so the text is not evidence of anything — which is exactly why the pointer
 * had to exist before 8C-3B could ask the question.
 *
 * Pure. No database, no clock, no server module: the same vocabulary is used by the
 * coordinator, by the snapshot schema and by the unit suite.
 */

// ---------------------------------------------------------------------------
// Where an announcement came from
// ---------------------------------------------------------------------------

/**
 * The closed source vocabulary — the table's `announcement_source_check`, restated.
 *
 * It lives here rather than in `./snapshot.ts` because provenance is what this module
 * is about, and because the pairing rule below needs it: a module that owns "which
 * override does this belong to" has to own "is it the kind that belongs to one at
 * all". `./snapshot.ts` imports it, and nothing imports back.
 */
export const ANNOUNCEMENT_SOURCES = ['manual', 'opening_hours'] as const

/**
 * Where a published announcement came from.
 *
 * `'manual'` — somebody wrote it at `/admin/besked` (1ad).
 * `'opening_hours'` — generated from a one-off opening-hours change (1t), by the
 * 8C-2 generator and the 8C-3A coordinator. Such an announcement **always** names the
 * override that owns it; see {@link AnnouncementOwnership}.
 */
export type AnnouncementSource = (typeof ANNOUNCEMENT_SOURCES)[number]

// ---------------------------------------------------------------------------
// The ownership state
// ---------------------------------------------------------------------------

/**
 * Where the announcement came from, as one value rather than two loose columns.
 *
 * The two columns can express states the model does not have — a manual announcement
 * with an owner, a generated one without — and `announcement_source_owner_check`
 * refuses both in the database. {@link announcementOwnershipOf} is the same refusal in
 * TypeScript: it returns `null` for a pair the model cannot hold, so a caller that
 * branches on the result cannot silently treat a broken row as manual.
 */
export type AnnouncementOwnership =
  /** Somebody wrote it at `/admin/besked`. No override is involved. */
  | { readonly kind: 'manual' }
  /** A one-off opening-hours change generated it, and this override owns it. */
  | { readonly kind: 'generated'; readonly overrideId: string }

/** The two columns, as the database holds them. */
export type AnnouncementOwnershipColumns = {
  readonly source: AnnouncementSource
  readonly source_override_id: string | null
}

/**
 * The ownership the two columns describe — or `null` when they describe nothing.
 *
 * `null` is not "manual". It is "this pair is not a state this system can be in", and
 * the only way to reach it is a row written by something other than
 * `replace_announcement()` or `restore_announcement()`.
 */
export function announcementOwnershipOf(
  columns: AnnouncementOwnershipColumns,
): AnnouncementOwnership | null {
  if (columns.source === 'manual') {
    return columns.source_override_id === null ? { kind: 'manual' } : null
  }

  return columns.source_override_id === null
    ? null
    : { kind: 'generated', overrideId: columns.source_override_id }
}

/** True when the two columns are a state the model can hold. */
export function isConsistentAnnouncementOwnership(
  columns: AnnouncementOwnershipColumns,
): boolean {
  return announcementOwnershipOf(columns) !== null
}

/**
 * §7e item 6's question, asked of ids.
 *
 * *"Default to removing the announcement too when `source='opening_hours'` and it
 * points at that date."* "Points at that date" is this function and nothing else: the
 * override's own id, compared to the one the singleton holds. **8C-3B** decides what
 * to do with a `true`; this decides what `true` means.
 */
export function isOwnedByOverride(
  columns: AnnouncementOwnershipColumns,
  overrideId: string,
): boolean {
  const ownership = announcementOwnershipOf(columns)

  return ownership !== null && ownership.kind === 'generated' && ownership.overrideId === overrideId
}

// ---------------------------------------------------------------------------
// What a replacement would displace
// ---------------------------------------------------------------------------

/**
 * What the announcement currently is, from the point of view of replacing it — the
 * four-way answer `public.announcement_replacement_kind()` gives, mirrored here so a
 * screen can name it without a second definition.
 *
 *   * `active`  — a message a guest can read right now. **The only public conflict**,
 *                 and the only case 1ae's sheet exists for.
 *   * `hidden`  — a valid, unexpired message that had been switched off.
 *   * `expired` — a message whose expiry has passed. No guest can see it.
 *   * `none`    — there is no message at all.
 *
 * The **server** decides which one it is, from the row it read, inside the same
 * transaction as the write. This type is the vocabulary, not the decision.
 */
export type ReplacedAnnouncementKind = 'active' | 'hidden' | 'expired' | 'none'

export const REPLACED_ANNOUNCEMENT_KINDS = [
  'active',
  'hidden',
  'expired',
  'none',
] as const satisfies readonly ReplacedAnnouncementKind[]

/**
 * Does replacing this require somebody to say so first? — §7e item 8.
 *
 * *"A conflict returns `{status:'conflict'}` and requires an explicit
 * `confirmReplace: true` on the follow-up call."* Only `active` does. A hidden or
 * expired message is not on anybody's screen, and asking a person to choose between
 * two messages when only one of them was ever visible would be a question about
 * nothing (§0k reading D).
 *
 * It is stated here **and** in `apply_generated_announcement()`, and the database's is
 * the one that decides: this exists so a screen can predict the answer, never so it
 * can supply it.
 */
export function replacementNeedsConfirmation(kind: ReplacedAnnouncementKind): boolean {
  return kind === 'active'
}
