-- ===========================================================================
-- Phase 8C-3A — who owns the generated announcement, and the transaction that
-- moves that ownership (§4, §5, §6, §7e items 6 and 8, §8; design 1t, 1ae)
--
-- 8C-1 built the mechanism that carries a replacement. 8C-2 built the pure
-- generator that composes one from a one-off opening-hours change. Neither
-- answered the question 8C-3 cannot proceed without:
--
--     announcement A was generated by override A and is live.
--     announcement B, generated by override B, replaces it.
--     Fortryd puts A back.
--     **Which override owns the announcement now?**
--
-- Nothing in the schema could answer that. `opening_hours_overrides.announcement_created`
-- is a boolean per override with no counterpart on the announcement, so it can say
-- "this override generated something" and cannot say "this override owns *that*".
-- The `previous` snapshot carried the eight published fields and no owner at all, so
-- a restore could put A's words back and had nothing to put A's provenance back from.
-- And §7e item 6 — *"default to removing the announcement too when
-- `source='opening_hours'` and it points at that date"* — was answerable only by
-- reading the message, which is editable and therefore not evidence of anything.
--
-- ---------------------------------------------------------------------------
-- THE MODEL: ONE POINTER, AND NO SECOND COPY OF THE SAME FACT
-- ---------------------------------------------------------------------------
--
-- `public.announcement.source_override_id` is the **only** representation of
-- generated-announcement ownership in this system.
--
--     source = 'manual'         ->  source_override_id is null
--     source = 'opening_hours'  ->  source_override_id names exactly one override
--
-- Both halves are a CHECK constraint, so neither can be true without the other.
--
-- `opening_hours_overrides.announcement_created` is **dropped**, and that is the
-- decision this migration turns on. It was §4's column for this job, and keeping it
-- would have cost two things and bought none:
--
--   * **It would be a second store of one fact.** With the pointer present,
--     "does this override own the current announcement?" is
--     `announcement.source_override_id = o.id` — derived, never stored, and therefore
--     never able to disagree with itself. A boolean beside it is a cache of a join,
--     and a cache that a failed statement can leave stale is exactly the state the
--     brief forbids: *announcement B is live but override A still says it owns it*.
--   * **It would need a second write guard.** `opening_hours_overrides` carries a
--     table-level `update` grant to `authenticated`, so a trusted `announcement_created`
--     would need the whole apparatus of `20260831160000_announcement_column_privileges.sql`
--     — a column grant and a BEFORE UPDATE trigger — built a second time, on a second
--     table, to protect a value that is already knowable without it. The pointer needs
--     none of that: it lives on `public.announcement`, where the guard already stands,
--     and joins it with one line.
--
-- "At most one override owns the current announcement" is therefore **structural**
-- rather than constrained. There is one announcement row (`announcement_singleton`),
-- it holds one `source_override_id`, and one column cannot hold two values. No partial
-- unique index is needed, and none is created: an index can only make a duplicate
-- unlikely to be written, and there is nowhere here for a duplicate to live.
--
-- ---------------------------------------------------------------------------
-- THE SNAPSHOT GAINS A NINTH KEY, AND IT IS THE SAME KEY
-- ---------------------------------------------------------------------------
--
-- §0k lists the five things `previous` deliberately excludes, and every one of those
-- reasons still holds. `source_override_id` is not one of them: it is part of the
-- published **state** in exactly the way `source` is, and §0k's own argument for
-- `source` — *"without it, a generated opening-hours message would come back calling
-- itself manual"* — applies unchanged one level down. Without the owner, a generated
-- message comes back owned by nobody, which the CHECK constraint would refuse outright.
--
-- Nine keys, then, and still: no `draft`, no nested `previous`, no `replaced_at`, no
-- `updated_at`, no `updated_by`. One level only.
--
-- ---------------------------------------------------------------------------
-- WHAT IS ADDED, AND WHAT IS NOT
-- ---------------------------------------------------------------------------
--
--   * `public.announcement_replacement_kind()` — the four-way answer
--     `replace_announcement()` already computed inline, lifted out so the coordinator
--     asks the same question rather than a second one that looks like it.
--   * `public.apply_generated_announcement()` — the coordinator §7e item 8 describes.
--     It inspects the singleton **server-side**, refuses with `conflict` when an active
--     announcement would be displaced and replacement was not explicitly confirmed, and
--     otherwise delegates to `replace_announcement()`. It composes no message, reads no
--     opening hours and computes no expiry: those are the generator's (8C-2), and the
--     Server Action reconstructs them before calling this.
--   * **No workflow engine.** The coordinator takes no table name, no column name, no
--     step list and no callback. It is one function for one operation, in the same
--     family as `set_weekly_special_sold_out()` and `remove_opening_hours_override()`.
--   * **No hours publication.** §7e item 8 is binding: *"the hours override is written
--     first and always; the announcement is only attempted afterwards"*. Nothing here
--     writes `public.opening_hours` or `public.opening_hours_overrides` at all, so
--     there is no statement through which an announcement conflict could roll a
--     published override back. The coordinator's own reply cannot reach the hours.
--   * **No conflict sheet, no checkbox, no Fortryd strip.** 1ae and 1t's *"Vis også som
--     besked øverst på hjemmesiden"* are **8C-3B**.
--   * **No SECURITY DEFINER.** Every function here is invoker-rights with
--     `search_path` pinned to nothing, exactly as §5 requires.
-- ===========================================================================


-- ===========================================================================
-- 1. The ownership column, and the flag it replaces
-- ===========================================================================
--
-- `on delete restrict` rather than `set null`: an override that still owns the live
-- announcement must not be deletable *at all* while it does, because the alternative
-- states are both wrong. `set null` would leave `source = 'opening_hours'` with no
-- owner — the CHECK below refuses that, so the DELETE would fail anyway, with a
-- constraint violation instead of a foreign-key one. `cascade` is not a candidate:
-- deleting the announcement row would break `announcement_singleton_unique`.
--
-- So the database's answer to "delete an override that owns the announcement" is
-- **no**, and `remove_opening_hours_override()` (§10 below) turns that into a status a
-- screen can act on. §7e item 6's *"ask, and default to removing the announcement
-- too"* is **8C-3B**: the model is what this migration provides, and the asking is
-- what 8C-3B builds on top of it.

alter table public.announcement
  add column source_override_id uuid references public.opening_hours_overrides (id) on delete restrict;

comment on column public.announcement.source_override_id is
  'The one-off opening-hours override that owns the current generated announcement, or null for a manual one. The single representation of generated-announcement ownership (technical plan section 4, section 7e item 6). Written only by replace_announcement() and restore_announcement().';

-- Both directions, in one constraint. A generated announcement without an owner and a
-- manual announcement with one are the same kind of mistake, and neither is storable.
alter table public.announcement
  add constraint announcement_source_owner_check check (
    (source = 'opening_hours' and source_override_id is not null)
    or (source = 'manual' and source_override_id is null)
  );

-- A `previous` written before this migration has eight keys and would fail the
-- nine-key validator, which would turn a pending Fortryd into `invalid_snapshot`. It
-- can only be a *manual* snapshot — nothing has ever written `source = 'opening_hours'`
-- outside a transaction that also cleared `previous` — so the ninth key is null, and
-- adding it is a faithful restatement rather than a guess.
update public.announcement
   set previous = previous || jsonb_build_object('source_override_id', null)
 where previous is not null
   and not (previous ? 'source_override_id');

-- §4's column for this job, retired. It was written by nothing in phases 1-8C-2 and
-- read by nothing at all; the header above records why the pointer replaces it rather
-- than joining it.
alter table public.opening_hours_overrides drop column announcement_created;


-- ===========================================================================
-- 2. The grant
-- ===========================================================================
--
-- Twelve columns now, for the reason `20260831160000` gives for the other eleven and
-- not for a new one: a SECURITY INVOKER function writes with its caller's privileges,
-- so a column `replace_announcement()` and `restore_announcement()` write is
-- necessarily a column `authenticated` holds UPDATE on. §5 below is what decides when
-- it may actually move.

grant update (source_override_id) on public.announcement to authenticated;


-- ===========================================================================
-- 3. announcement_snapshot — nine keys
-- ===========================================================================

create or replace function public.announcement_snapshot(a public.announcement)
returns jsonb language sql stable security invoker set search_path = ''
as $fn$
  select jsonb_build_object(
    'message',            a.message,
    'link_type',          a.link_type,
    'link_page',          a.link_page,
    'link_url',           a.link_url,
    'link_label',         a.link_label,
    'expires_at',         a.expires_at,
    'is_visible',         a.is_visible,
    'source',             a.source,
    'source_override_id', a.source_override_id)
$fn$;

comment on function public.announcement_snapshot(public.announcement) is
  'The published content, state and ownership of the announcement, as the previous-snapshot shape and as the replace/restore audit pair (technical plan section 6). Nine keys, no draft, no nested previous, no actor and no concurrency token.';


-- ===========================================================================
-- 4. is_valid_announcement_snapshot — the same nine, read the other way
-- ===========================================================================
--
-- The ninth key is checked the way the column is: a uuid or null, paired with `source`
-- in both directions. A snapshot that could not be written back into the columns is
-- not a snapshot this system produced, and `announcement_source_owner_check` is now
-- one of the columns' rules it has to satisfy.

create or replace function public.is_valid_announcement_snapshot(s jsonb)
returns boolean
language plpgsql
stable
security invoker
set search_path = ''
as $fn$
declare
  v_keys      text[];
  v_link_type text;
  v_message   text;
  v_page      text;
  v_url       text;
  v_owner     text;
  v_source    text;
  v_ignored   timestamptz;
  v_uuid      uuid;
begin
  if s is null or jsonb_typeof(s) <> 'object' then return false; end if;

  select array_agg(k order by k) into v_keys from jsonb_object_keys(s) k;

  if v_keys is distinct from array[
       'expires_at', 'is_visible', 'link_label', 'link_page',
       'link_type', 'link_url', 'message', 'source', 'source_override_id']::text[]
  then return false; end if;

  if jsonb_typeof(s -> 'is_visible') <> 'boolean' then return false; end if;
  if jsonb_typeof(s -> 'link_type')  <> 'string'  then return false; end if;
  if jsonb_typeof(s -> 'source')     <> 'string'  then return false; end if;

  if jsonb_typeof(s -> 'message')    not in ('string', 'null') then return false; end if;
  if jsonb_typeof(s -> 'link_page')  not in ('string', 'null') then return false; end if;
  if jsonb_typeof(s -> 'link_url')   not in ('string', 'null') then return false; end if;
  if jsonb_typeof(s -> 'link_label') not in ('string', 'null') then return false; end if;
  if jsonb_typeof(s -> 'expires_at') not in ('string', 'null') then return false; end if;
  if jsonb_typeof(s -> 'source_override_id') not in ('string', 'null') then return false; end if;

  v_message   := s ->> 'message';
  v_link_type := s ->> 'link_type';
  v_page      := s ->> 'link_page';
  v_url       := s ->> 'link_url';
  v_source    := s ->> 'source';
  v_owner     := s ->> 'source_override_id';

  if v_message is not null and length(v_message) > 90 then return false; end if;
  if v_link_type not in ('none', 'page', 'url') then return false; end if;
  if v_source not in ('manual', 'opening_hours') then return false; end if;

  -- `announcement_source_owner_check`, restated. A stored snapshot that failed this
  -- is one a restore could not write back into the row.
  if (v_source = 'opening_hours') is distinct from (v_owner is not null) then
    return false;
  end if;

  if v_owner is not null then
    begin
      v_uuid := v_owner::uuid;
    exception when others then
      return false;
    end;
  end if;

  if not (
       (v_link_type = 'none' and v_page is null and v_url is null)
    or (v_link_type = 'page' and v_page is not null and v_url is null)
    or (v_link_type = 'url'  and v_url  is not null and v_page is null))
  then return false; end if;

  if v_page is not null
     and v_page not in ('/', '/menu', '/mad-ud-af-huset', '/om-os', '/nyheder', '/find-os')
  then return false; end if;

  if v_url is not null and v_url !~ '^https://[^\s]+$' then return false; end if;

  if s ->> 'expires_at' is not null then
    begin
      v_ignored := (s ->> 'expires_at')::timestamptz;
    exception when others then
      return false;
    end;
  end if;

  return true;
end;
$fn$;

comment on function public.is_valid_announcement_snapshot(jsonb) is
  'True when a jsonb value is exactly an announcement snapshot: the nine keys announcement_snapshot() writes, each of the right type, and the same rules the columns CHECK - including the source/source_override_id pairing. Asked before a snapshot is stored and again before one is restored.';


-- ===========================================================================
-- 5. The write guard — ownership is provenance, and moves with it
-- ===========================================================================
--
-- `source_override_id` joins `source` under the same transition, because they are one
-- fact stored in two columns: an announcement's provenance is *what kind* it is and
-- *which override* it came from, and a write that could move one without the other
-- would be able to produce exactly the states `announcement_source_owner_check`
-- exists to refuse.
--
-- It is a **trusted lifecycle field** in §0l's sense, and for §0l's reason:
-- `restore_announcement()` reads it back out of `previous` and writes it into the row
-- without asking anything else about it, and §7e item 6 will decide whether to remove
-- a live announcement by reading it. A Staff member who could set it directly could
-- make any override appear to own any announcement — and then have the deletion of
-- that override take a message down, or refuse to. So a direct PostgREST UPDATE owns
-- `draft`, and still owns nothing else.
--
-- Every other line of this function is byte-identical to the 8C-1 hardening pass.

create or replace function public.tg_guard_announcement_write()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $fn$
declare
  v_op        text;
  v_content   boolean;
  v_visible   boolean;
  v_source    boolean;
  v_lifecycle boolean;
begin
  if current_user not in ('anon', 'authenticated') then
    return new;
  end if;

  v_op := pg_catalog.current_setting('app.announcement_write', true);

  if v_op is not null and v_op <> '' then
    perform pg_catalog.set_config('app.announcement_write', '', true);
  end if;

  v_op        := coalesce(v_op, '');
  v_content   := v_op in ('publish', 'replace', 'restore');
  v_visible   := v_op in ('publish', 'visibility', 'replace', 'restore');
  v_source    := v_op in ('replace', 'restore');
  v_lifecycle := v_op in ('replace', 'restore');

  if not v_content and (
       new.message    is distinct from old.message
    or new.link_type  is distinct from old.link_type
    or new.link_page  is distinct from old.link_page
    or new.link_url   is distinct from old.link_url
    or new.link_label is distinct from old.link_label
    or new.expires_at is distinct from old.expires_at)
  then
    raise exception
      'announcement: the published message, its link and its expiry are written only by publish_announcement(), replace_announcement() or restore_announcement()'
      using errcode = '42501';
  end if;

  if not v_visible and new.is_visible is distinct from old.is_visible then
    raise exception
      'announcement: is_visible is written only by set_announcement_visible(), publish_announcement(), replace_announcement() or restore_announcement()'
      using errcode = '42501';
  end if;

  -- Provenance: what kind of announcement this is, and which override owns it.
  if not v_source and (
       new.source             is distinct from old.source
    or new.source_override_id is distinct from old.source_override_id)
  then
    raise exception
      'announcement: source and source_override_id are written only by replace_announcement() or restore_announcement()'
      using errcode = '42501';
  end if;

  if not v_lifecycle and (
       new.previous    is distinct from old.previous
    or new.replaced_at is distinct from old.replaced_at)
  then
    raise exception
      'announcement: previous and replaced_at are written only by replace_announcement() or restore_announcement()'
      using errcode = '42501';
  end if;

  return new;
end;
$fn$;

comment on function public.tg_guard_announcement_write() is
  'BEFORE UPDATE on public.announcement: refuses any movement of the published, visibility, provenance (source and source_override_id) and lifecycle columns that did not come from the lifecycle function owning it. A direct PostgREST write owns draft and nothing else (technical plan section 5, section 8).';


-- ===========================================================================
-- 6. announcement_replacement_kind — the four-way answer, stated once
-- ===========================================================================
--
-- `replace_announcement()` computed this inline; the coordinator has to ask the same
-- question, and §6 of the brief says so in as many words: *"Use the same definition of
-- active/public conflict that Phase 7 already uses."* Two copies of a four-branch CASE
-- is how those two definitions start to drift, so there is one.
--
--   'none'    — no message at all
--   'expired' — a message whose expiry has passed; no guest can read it
--   'hidden'  — a valid, unexpired message that was switched off
--   'active'  — a message a guest can read right now. The only public conflict.
--
-- The order matters and is the order `announcement_select_public` reads in: a blank
-- message is nothing whatever its other columns say, and an expired message is not a
-- conflict even while `is_visible` is true.

create or replace function public.announcement_replacement_kind(a public.announcement)
returns text language sql stable security invoker set search_path = ''
as $fn$
  select case
    when a.message is null or pg_catalog.btrim(a.message) = ''    then 'none'
    when a.expires_at is null or a.expires_at <= pg_catalog.now() then 'expired'
    when not a.is_visible                                         then 'hidden'
    else 'active'
  end
$fn$;

comment on function public.announcement_replacement_kind(public.announcement) is
  'What replacing the current announcement would displace: none, expired, hidden or active. Active is the only public conflict (design 1ae, technical plan section 7e item 8). Asked by replace_announcement() and by apply_generated_announcement(), so the two cannot disagree.';


-- ===========================================================================
-- 7. replace_announcement — the owner is the source's other half
-- ===========================================================================
--
-- One new parameter, appended, and it is the only change to this function besides the
-- lifted CASE: `p_source_override_id`, which the payload rules now pair with
-- `p_source` in both directions before anything is read.
--
-- **It is appended and defaulted to null on purpose.** A caller that says nothing
-- about ownership is saying "manual", which is the safe half of the pair: with
-- `p_source = 'manual'` the omission is correct, and with `p_source = 'opening_hours'`
-- it is `invalid_payload` rather than an unowned generated announcement. There is no
-- value of the default that produces a wrong write.
--
-- The override must **exist and be published**. That is §7e item 8's ordering made
-- structural rather than promised: an announcement describing hours that are not on
-- the hjemmeside is the one outcome the item forbids, and this is the statement that
-- makes it unwritable. `restore_announcement()` deliberately does *not* re-ask — see
-- §8.

drop function if exists public.replace_announcement(
  text, text, text, text, text, timestamptz, text, timestamptz);

create or replace function public.replace_announcement(
  p_message             text,
  p_link_type           text,
  p_link_page           text,
  p_link_url            text,
  p_link_label          text,
  p_expires_at          timestamptz,
  p_source              text,
  p_expected_updated_at timestamptz,
  p_source_override_id  uuid default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $fn$
declare
  v_row      public.announcement%rowtype;
  v_id       uuid;
  v_previous jsonb;
  v_after    jsonb;
  v_replaced text;
  v_written  boolean;
begin
  if p_message is null or pg_catalog.btrim(p_message) = '' then
    return jsonb_build_object('status', 'invalid_payload', 'reason', 'message');
  end if;

  if length(p_message) > 90 then
    return jsonb_build_object('status', 'invalid_payload', 'reason', 'message_length');
  end if;

  if p_expires_at is null or p_expires_at <= pg_catalog.now() then
    return jsonb_build_object('status', 'invalid_payload', 'reason', 'expires_at');
  end if;

  if p_source is null or p_source not in ('manual', 'opening_hours') then
    return jsonb_build_object('status', 'invalid_payload', 'reason', 'source');
  end if;

  -- The pairing rule, both ways. `announcement_source_owner_check` would refuse the
  -- write anyway; refusing here makes it a status a person can be told rather than a
  -- constraint violation that rolls the transaction back.
  if (p_source = 'opening_hours') is distinct from (p_source_override_id is not null) then
    return jsonb_build_object('status', 'invalid_payload', 'reason', 'source_override');
  end if;

  -- The hours are published first and always (§7e item 8). An override that is not
  -- live cannot own a message describing it as live.
  if p_source_override_id is not null
     and not exists (select 1 from public.opening_hours_overrides o
                      where o.id = p_source_override_id and o.status = 'published')
  then
    return jsonb_build_object('status', 'invalid_payload', 'reason', 'source_override');
  end if;

  if p_link_type is null or p_link_type not in ('none', 'page', 'url') then
    return jsonb_build_object('status', 'invalid_payload', 'reason', 'link');
  end if;

  if not (
       (p_link_type = 'none' and p_link_page is null and p_link_url is null)
    or (p_link_type = 'page' and p_link_page is not null and p_link_url is null)
    or (p_link_type = 'url'  and p_link_url  is not null and p_link_page is null))
  then
    return jsonb_build_object('status', 'invalid_payload', 'reason', 'link');
  end if;

  if p_link_page is not null
     and p_link_page not in ('/', '/menu', '/mad-ud-af-huset', '/om-os', '/nyheder', '/find-os')
  then
    return jsonb_build_object('status', 'invalid_payload', 'reason', 'link');
  end if;

  if p_link_url is not null and p_link_url !~ '^https://[^\s]+$' then
    return jsonb_build_object('status', 'invalid_payload', 'reason', 'link');
  end if;

  if p_link_type = 'url' and (p_link_label is null or pg_catalog.btrim(p_link_label) = '') then
    return jsonb_build_object('status', 'invalid_payload', 'reason', 'link_label');
  end if;

  select * into v_row from public.announcement t limit 1;
  if not found then return jsonb_build_object('status', 'not_found'); end if;

  v_id := v_row.id;

  if p_expected_updated_at is null or v_row.updated_at is distinct from p_expected_updated_at then
    return jsonb_build_object('status', 'conflict', 'updated_at', v_row.updated_at);
  end if;

  v_replaced := public.announcement_replacement_kind(v_row);
  v_previous := public.announcement_snapshot(v_row);

  if not public.is_valid_announcement_snapshot(v_previous) then
    return jsonb_build_object('status', 'invalid_snapshot');
  end if;

  perform pg_catalog.set_config('app.announcement_write', 'replace', true);

  -- Eleven columns, named. `draft` is not one of them, so a pending manual
  -- announcement survives a replacement byte for byte. Ownership moves in the same
  -- statement as the content and the source, so there is no instant in which
  -- announcement B is live and override A still owns it.
  update public.announcement t set
    message            = p_message,
    link_type          = p_link_type,
    link_page          = p_link_page,
    link_url           = p_link_url,
    link_label         = p_link_label,
    expires_at         = p_expires_at,
    source             = p_source,
    source_override_id = p_source_override_id,
    is_visible         = true,
    previous           = v_previous,
    replaced_at        = pg_catalog.now()
   where t.id = v_id
     and t.updated_at = p_expected_updated_at
  returning * into v_row;

  v_written := found;
  perform pg_catalog.set_config('app.announcement_write', '', true);

  if not v_written then
    if exists (select 1 from public.announcement t
                where t.id = v_id and t.updated_at = p_expected_updated_at)
    then return jsonb_build_object('status', 'forbidden'); end if;
    return jsonb_build_object('status', 'conflict');
  end if;

  v_after := public.announcement_snapshot(v_row);
  perform public.log_audit('replace', 'announcement', v_id, v_previous, v_after);

  return jsonb_build_object(
    'status',             'replaced',
    'entity_id',          v_id,
    'updated_at',         v_row.updated_at,
    'replaced',           v_replaced,
    'replaced_at',        v_row.replaced_at,
    'source_override_id', v_row.source_override_id,
    'before',             v_previous,
    'after',              v_after);
end;
$fn$;

comment on function public.replace_announcement(text, text, text, text, text, timestamptz, text, timestamptz, uuid) is
  'Replaces the published announcement with another already-validated one, stashes the current published state and ownership in previous, stamps replaced_at, makes the replacement visible and audits it - one transaction (design 1ae, technical plan section 6). Takes typed scalars, never a json document; pairs source with source_override_id in both directions; never touches draft; keeps exactly one level of previous. The only statement in the system that may write previous or move ownership onto an override.';


-- ===========================================================================
-- 8. restore_announcement — ownership comes back with the message
-- ===========================================================================
--
-- The snapshot's ninth key is restored in the same statement as the other eight, so
-- 1ae's Fortryd puts back **both** halves of what was displaced: what the bar said,
-- and which override it belonged to. There is no second UPDATE, no second transaction
-- and no ownership bookkeeping outside this statement — which is what makes the
-- brief's *"A returns, A owns it again, B does not"* a property of the schema rather
-- than of a script that could fail halfway.
--
-- TWO THINGS IT DELIBERATELY DOES NOT RE-ASK
--
--   * **Whether the owning override is still published.** It was when the replacement
--     was made; the previous state is a fact rather than a request, exactly as §0k
--     reading C says of the expiry. `status` never moves backwards in this model, so
--     there is nothing here to be stale.
--   * **Whether the expiry has passed.** Unchanged from 8C-1. `showable` reports it.
--
-- ONE THING IT NOW HAS TO ASK
--
-- `previous` is jsonb, so the foreign key does not reach into it. An override that
-- owned announcement A, was displaced by B, and was then deleted — which the foreign
-- key allows, because it no longer owns anything — leaves a snapshot naming a row that
-- is gone. Restoring it would raise a foreign-key violation and roll the transaction
-- back with nothing for a person to read, so the case is named instead:
-- `owner_missing`, nothing written, nothing logged, and the snapshot left exactly
-- where it is. `remove_opening_hours_override()` refuses that deletion (§10), so the
-- only way to reach this status is a direct PostgREST DELETE.

create or replace function public.restore_announcement(p_expected_updated_at timestamptz)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $fn$
declare
  v_row      public.announcement%rowtype;
  v_id       uuid;
  v_snapshot jsonb;
  v_before   jsonb;
  v_after    jsonb;
  v_owner    uuid;
  v_written  boolean;
begin
  select * into v_row from public.announcement t limit 1;
  if not found then return jsonb_build_object('status', 'not_found'); end if;

  v_id := v_row.id;

  if p_expected_updated_at is null or v_row.updated_at is distinct from p_expected_updated_at then
    return jsonb_build_object('status', 'conflict', 'updated_at', v_row.updated_at);
  end if;

  v_snapshot := v_row.previous;

  if v_snapshot is null then
    return jsonb_build_object('status', 'nothing_to_restore');
  end if;

  if not public.is_valid_announcement_snapshot(v_snapshot) then
    -- Refused safely: no write, no audit row, and the malformed value is not
    -- discarded. Whatever put it there is a bug worth being able to look at, and a
    -- restore is not the place to tidy away evidence.
    return jsonb_build_object('status', 'invalid_snapshot');
  end if;

  v_owner := (v_snapshot ->> 'source_override_id')::uuid;

  if v_owner is not null
     and not exists (select 1 from public.opening_hours_overrides o where o.id = v_owner)
  then
    return jsonb_build_object('status', 'owner_missing');
  end if;

  v_before := public.announcement_snapshot(v_row);

  perform pg_catalog.set_config('app.announcement_write', 'restore', true);

  update public.announcement t set
    message            = v_snapshot ->> 'message',
    link_type          = v_snapshot ->> 'link_type',
    link_page          = v_snapshot ->> 'link_page',
    link_url           = v_snapshot ->> 'link_url',
    link_label         = v_snapshot ->> 'link_label',
    expires_at         = (v_snapshot ->> 'expires_at')::timestamptz,
    is_visible         = (v_snapshot ->> 'is_visible')::boolean,
    source             = v_snapshot ->> 'source',
    source_override_id = v_owner,
    previous           = null,
    replaced_at        = null
   where t.id = v_id
     and t.updated_at = p_expected_updated_at
  returning * into v_row;

  v_written := found;
  perform pg_catalog.set_config('app.announcement_write', '', true);

  if not v_written then
    if exists (select 1 from public.announcement t
                where t.id = v_id and t.updated_at = p_expected_updated_at)
    then return jsonb_build_object('status', 'forbidden'); end if;
    return jsonb_build_object('status', 'conflict');
  end if;

  v_after := public.announcement_snapshot(v_row);
  perform public.log_audit('restore', 'announcement', v_id, v_before, v_after);

  return jsonb_build_object(
    'status',             'restored',
    'entity_id',          v_id,
    'updated_at',         v_row.updated_at,
    'source_override_id', v_row.source_override_id,
    'showable',           (v_row.is_visible
                           and v_row.message is not null
                           and v_row.expires_at is not null
                           and v_row.expires_at > pg_catalog.now()),
    'before',             v_before,
    'after',              v_after);
end;
$fn$;

comment on function public.restore_announcement(timestamptz) is
  'Puts back the announcement stashed in previous - its content, its state and its owning override - clears previous and replaced_at, and audits it, one transaction (design 1ae, technical plan section 6). Reads the snapshot from the database; the browser sends no content and no owner. Never extends an expiry to make itself succeed, and never touches draft.';


-- ===========================================================================
-- 9. apply_generated_announcement — the coordinator (§7e item 8)
-- ===========================================================================
--
-- The second half of §7e item 8, and only the second half:
--
--     "Server-authoritative: the hours override is written first and always; the
--      announcement is only attempted afterwards; a conflict returns
--      {status:'conflict'} and requires an explicit confirmReplace: true on the
--      follow-up call. There is no code path where a 'Behold eksisterende' choice can
--      roll back the hours."
--
-- **Nothing here publishes an override.** The caller has already done that, and this
-- function cannot undo it: it issues no statement against `public.opening_hours` or
-- `public.opening_hours_overrides` at all, so "Behold eksisterende" is a branch that
-- returns rather than a branch that rolls anything back. Refusing costs the hours
-- nothing, because there is no statement here that could cost them anything.
--
-- WHAT IT DECIDES, AND WHAT IT REFUSES TO BE TOLD
--
-- The conflict is decided from the row this function reads, through
-- `announcement_replacement_kind()`. The browser's opinion about whether there is a
-- message on the hjemmeside is not a parameter and cannot be one. What the caller may
-- say is one bit — *"I have been shown the conflict and I still want to replace"* —
-- and it is only consulted for `active`.
--
--     kind = 'active'  and not confirmed     ->  conflict, zero writes, no audit row
--     kind = 'active'  and confirmed         ->  applied
--     kind in ('hidden', 'expired', 'none')  ->  applied, no sheet, no confirmation
--
-- `hidden` and `expired` are not public conflicts (§0k reading D): no guest can read
-- either, so asking a person to choose between two messages when only one of them was
-- ever on screen would be a question about nothing. Both are still snapshotted
-- faithfully, so Fortryd puts back exactly what was there.
--
-- WHAT THE BROWSER DOES NOT CONTROL
--
-- Not `source` — this function writes `'opening_hours'` and takes no parameter for it.
-- Not the ownership, which is the override it was given and never a second id. Not
-- `previous`, not `replaced_at`, not `is_visible`, not `draft`. The message, link,
-- label and expiry **are** parameters, and that is deliberate: 8C-3B lets a staff
-- member edit the suggested wording before using it, so a message string has to be
-- able to travel. The reconstruction rule lives above this function, in the Server
-- Action, which re-reads the published override and the recurring week and asks the
-- 8C-2 generator for the link and the expiry rather than believing a form. What this
-- function guarantees is narrower and absolute: the announcement it writes is owned by
-- the override named, that override is published, and the write is one transaction
-- with the ownership move.
--
-- THE OVERRIDE'S OWN VERSION TOKEN
--
-- `p_override_expected_updated_at` is optimistic concurrency (§6) on the *hours*, not
-- on the announcement. The Server Action read that override in order to generate the
-- message; if somebody has edited or republished it since, the words this call is
-- carrying may no longer describe it, and `stale_override` says so rather than
-- publishing a sentence about hours nobody has.

create or replace function public.apply_generated_announcement(
  p_override_id                  uuid,
  p_override_expected_updated_at timestamptz,
  p_message                      text,
  p_link_type                    text,
  p_link_page                    text,
  p_link_url                     text,
  p_link_label                   text,
  p_expires_at                   timestamptz,
  p_expected_updated_at          timestamptz,
  p_confirm_replace              boolean default false
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $fn$
declare
  v_override public.opening_hours_overrides%rowtype;
  v_row      public.announcement%rowtype;
  v_kind     text;
  v_result   jsonb;
  v_status   text;
begin
  if p_override_id is null then
    return jsonb_build_object('status', 'invalid_payload', 'reason', 'source_override');
  end if;

  -- Read through the caller's own JWT: `overrides_select_staff` is what decides this
  -- row exists at all, so a caller who may not see it gets `not_found` rather than a
  -- fact about the schedule.
  select * into v_override from public.opening_hours_overrides t where t.id = p_override_id;
  if not found then
    return jsonb_build_object('status', 'not_found', 'subject', 'override');
  end if;

  if p_override_expected_updated_at is null
     or v_override.updated_at is distinct from p_override_expected_updated_at
  then
    return jsonb_build_object('status', 'stale_override', 'updated_at', v_override.updated_at);
  end if;

  select * into v_row from public.announcement t limit 1;
  if not found then
    return jsonb_build_object('status', 'not_found', 'subject', 'announcement');
  end if;

  if p_expected_updated_at is null or v_row.updated_at is distinct from p_expected_updated_at then
    return jsonb_build_object('status', 'stale_announcement', 'updated_at', v_row.updated_at);
  end if;

  v_kind := public.announcement_replacement_kind(v_row);

  -- The first attempt never replaces a message a guest can read. Zero writes, no audit
  -- row, and the hours the caller published a moment ago are untouched — there is no
  -- statement in this branch at all.
  if v_kind = 'active' and not coalesce(p_confirm_replace, false) then
    return jsonb_build_object(
      'status',     'conflict',
      'conflict',   v_kind,
      'updated_at', v_row.updated_at,
      'current',    public.announcement_snapshot(v_row));
  end if;

  -- Composed rather than copied: every payload rule, the snapshot, `replaced_at`, the
  -- visibility, the audit row and the ownership move are `replace_announcement()`'s,
  -- unchanged. This function adds the conflict decision and nothing else.
  v_result := public.replace_announcement(
    p_message, p_link_type, p_link_page, p_link_url, p_link_label,
    p_expires_at, 'opening_hours', p_expected_updated_at, p_override_id);

  v_status := v_result ->> 'status';

  if v_status = 'replaced' then
    return v_result || jsonb_build_object('status', 'applied', 'conflict', v_kind);
  end if;

  -- The inner `conflict` is a *version* conflict, and this function's own `conflict`
  -- is 1ae's. Two different questions must not answer to one word.
  if v_status = 'conflict' then
    return jsonb_build_object('status', 'stale_announcement');
  end if;

  return v_result;
end;
$fn$;

comment on function public.apply_generated_announcement(uuid, timestamptz, text, text, text, text, text, timestamptz, timestamptz, boolean) is
  'Coordinates the generated opening-hours announcement after its override is already published (technical plan section 7e item 8): re-reads the singleton, returns conflict when an active announcement would be displaced and replacement was not confirmed, and otherwise delegates to replace_announcement() so the content, the snapshot and the ownership move in one transaction. Writes no opening hours, so no refusal here can roll a published override back.';


-- ===========================================================================
-- 10. remove_opening_hours_override — it refuses while it owns
-- ===========================================================================
--
-- §7e item 6 is 8C-3B's: *"Ask, and default to removing the announcement too."* This
-- migration builds the model that question needs and stops short of asking it, so the
-- honest behaviour in the meantime is a refusal a screen can word — not a raw foreign
-- key violation, and certainly not a silent orphaning.
--
-- Two ways an override can be holding an announcement, and both are refused:
--
--   * it **owns the current one** — `announcement.source_override_id` names it. The
--     foreign key would refuse the DELETE anyway; this turns `23503` into a status.
--   * it owns the one **stashed in `previous`** — a Fortryd is still on offer, and
--     deleting the row now would turn that Fortryd into `owner_missing`. The foreign
--     key does not reach inside jsonb, so this check is the only thing that does.
--
-- The pre-check is not a lock. Two sessions racing — one deleting the override, one
-- replacing the announcement onto it — can still meet the foreign key, which is the
-- backstop and refuses rather than corrupting. That is the correct order of defences:
-- the check gives a person a sentence, and the constraint gives the schema a promise.
--
-- Everything else about this function is phase 8B's, unchanged.

create or replace function public.remove_opening_hours_override(
  p_id                  uuid,
  p_expected_updated_at timestamptz
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $fn$
declare
  v_row    public.opening_hours_overrides%rowtype;
  v_before jsonb;
begin
  select * into v_row from public.opening_hours_overrides t where t.id = p_id;
  if not found then return jsonb_build_object('status', 'not_found'); end if;

  if p_expected_updated_at is null or v_row.updated_at is distinct from p_expected_updated_at then
    return jsonb_build_object('status', 'conflict', 'updated_at', v_row.updated_at);
  end if;

  -- The snapshot half is compared **as text**, deliberately. A cast to `uuid` would
  -- raise `22P02` on a malformed `previous` — a value only a service-role script or a
  -- future migration could have written, but one this function must not fail on — and
  -- `announcement_snapshot()` writes the id in its canonical lowercase form, so the two
  -- renderings cannot disagree.
  if exists (select 1 from public.announcement a
              where a.source_override_id = p_id
                 or a.previous ->> 'source_override_id' = p_id::text)
  then
    return jsonb_build_object('status', 'owns_announcement', 'entity_id', p_id);
  end if;

  v_before := public.opening_hours_override_content(v_row);

  delete from public.opening_hours_overrides t
   where t.id = p_id
     and t.updated_at = p_expected_updated_at;

  if not found then
    -- The pre-check passed, so either RLS refused the delete or another session moved
    -- the row first. The probe tells them apart, so the person is told which happened.
    if exists (select 1 from public.opening_hours_overrides t
                where t.id = p_id and t.updated_at = p_expected_updated_at)
    then return jsonb_build_object('status', 'forbidden'); end if;
    return jsonb_build_object('status', 'conflict');
  end if;

  perform public.log_audit('delete', 'opening_hours_override', p_id, v_before, null);

  return jsonb_build_object(
    'status', 'removed',
    'entity_id', p_id,
    'was_published', v_before ->> 'status' = 'published',
    'before', v_before);
end;
$fn$;

comment on function public.remove_opening_hours_override(uuid, timestamptz) is
  'Removes one one-off opening-hours change so the date follows the weekly schedule again. One transaction, audited, SECURITY INVOKER (section 7e item 6). Refuses with owns_announcement while the override owns the current announcement or the one stashed for Fortryd; deciding what to do about that is 8C-3B.';


-- ===========================================================================
-- 11. Privileges
-- ===========================================================================
--
-- `authenticated` only, and `anon` revoked explicitly rather than left to the default,
-- exactly as every phase since 4 has granted its own. An anonymous caller meets
-- `42501` at the function, before RLS is consulted.
--
-- `announcement.source_override_id` is **not** added to `anon`'s SELECT grant: a guest
-- reads the six columns the bar needs, and which override composed a message is
-- administration state.

revoke all on function public.announcement_replacement_kind(public.announcement) from public, anon;
revoke all on function public.replace_announcement(
  text, text, text, text, text, timestamptz, text, timestamptz, uuid) from public, anon;
revoke all on function public.apply_generated_announcement(
  uuid, timestamptz, text, text, text, text, text, timestamptz, timestamptz, boolean) from public, anon;

grant execute on function public.announcement_replacement_kind(public.announcement) to authenticated;
grant execute on function public.replace_announcement(
  text, text, text, text, text, timestamptz, text, timestamptz, uuid) to authenticated;
grant execute on function public.apply_generated_announcement(
  uuid, timestamptz, text, text, text, text, text, timestamptz, timestamptz, boolean) to authenticated;
